# Generated by Django 5.1.5 on 2026-08-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='banner',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
