# Generated by Django 5.1.5 on 2026-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_banner_deleted_at_remove_banner_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('combo_reduced_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veg', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('foods', models.ManyToManyField(related_name='combos', to='food.food')),
            ],
            options={
                'db_table': 'combo',
            },
        ),
    ]
