# Generated by Django 5.0.14 on 2026-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
